# Local run: web app and Storybook as Docker containers
# Usage: docker compose -f docker/docker-compose.yml up --build
services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      target: serve
    ports:
      - "8080:80"

  storybook:
    build:
      context: ..
      dockerfile: docker/storybook.Dockerfile
      target: serve
    ports:
      - "8081:80"
